// Warehouse Constants
export const WAREHOUSE_LIST_REQUEST = 'WAREHOUSE_LIST_REQUEST';
export const WAREHOUSE_LIST_SUCCESS = 'WAREHOUSE_LIST_SUCCESS';
export const WAREHOUSE_LIST_FAIL = 'WAREHOUSE_LIST_FAIL';

export const WAREHOUSE_DETAILS_REQUEST = 'WAREHOUSE_DETAILS_REQUEST';
export const WAREHOUSE_DETAILS_SUCCESS = 'WAREHOUSE_DETAILS_SUCCESS';
export const WAREHOUSE_DETAILS_FAIL = 'WAREHOUSE_DETAILS_FAIL';

export const WAREHOUSE_CREATE_REQUEST = 'WAREHOUSE_CREATE_REQUEST';
export const WAREHOUSE_CREATE_SUCCESS = 'WAREHOUSE_CREATE_SUCCESS';
export const WAREHOUSE_CREATE_FAIL = 'WAREHOUSE_CREATE_FAIL';

export const WAREHOUSE_UPDATE_REQUEST = 'WAREHOUSE_UPDATE_REQUEST';
export const WAREHOUSE_UPDATE_SUCCESS = 'WAREHOUSE_UPDATE_SUCCESS';
export const WAREHOUSE_UPDATE_FAIL = 'WAREHOUSE_UPDATE_FAIL';

export const WAREHOUSE_DELETE_REQUEST = 'WAREHOUSE_DELETE_REQUEST';
export const WAREHOUSE_DELETE_SUCCESS = 'WAREHOUSE_DELETE_SUCCESS';
export const WAREHOUSE_DELETE_FAIL = 'WAREHOUSE_DELETE_FAIL';

export const WAREHOUSE_INVENTORY_REQUEST = 'WAREHOUSE_INVENTORY_REQUEST';
export const WAREHOUSE_INVENTORY_SUCCESS = 'WAREHOUSE_INVENTORY_SUCCESS';
export const WAREHOUSE_INVENTORY_FAIL = 'WAREHOUSE_INVENTORY_FAIL';

export const WAREHOUSE_STATS_REQUEST = 'WAREHOUSE_STATS_REQUEST';
export const WAREHOUSE_STATS_SUCCESS = 'WAREHOUSE_STATS_SUCCESS';
export const WAREHOUSE_STATS_FAIL = 'WAREHOUSE_STATS_FAIL';

export const WAREHOUSE_SET_PRIMARY_REQUEST = 'WAREHOUSE_SET_PRIMARY_REQUEST';
export const WAREHOUSE_SET_PRIMARY_SUCCESS = 'WAREHOUSE_SET_PRIMARY_SUCCESS';
export const WAREHOUSE_SET_PRIMARY_FAIL = 'WAREHOUSE_SET_PRIMARY_FAIL';

// Warehouse Stock Constants
export const WAREHOUSE_STOCK_LIST_REQUEST = 'WAREHOUSE_STOCK_LIST_REQUEST';
export const WAREHOUSE_STOCK_LIST_SUCCESS = 'WAREHOUSE_STOCK_LIST_SUCCESS';
export const WAREHOUSE_STOCK_LIST_FAIL = 'WAREHOUSE_STOCK_LIST_FAIL';

export const WAREHOUSE_STOCK_DETAILS_REQUEST = 'WAREHOUSE_STOCK_DETAILS_REQUEST';
export const WAREHOUSE_STOCK_DETAILS_SUCCESS = 'WAREHOUSE_STOCK_DETAILS_SUCCESS';
export const WAREHOUSE_STOCK_DETAILS_FAIL = 'WAREHOUSE_STOCK_DETAILS_FAIL';

export const WAREHOUSE_STOCK_LOW_REQUEST = 'WAREHOUSE_STOCK_LOW_REQUEST';
export const WAREHOUSE_STOCK_LOW_SUCCESS = 'WAREHOUSE_STOCK_LOW_SUCCESS';
export const WAREHOUSE_STOCK_LOW_FAIL = 'WAREHOUSE_STOCK_LOW_FAIL';

export const WAREHOUSE_STOCK_OUT_REQUEST = 'WAREHOUSE_STOCK_OUT_REQUEST';
export const WAREHOUSE_STOCK_OUT_SUCCESS = 'WAREHOUSE_STOCK_OUT_SUCCESS';
export const WAREHOUSE_STOCK_OUT_FAIL = 'WAREHOUSE_STOCK_OUT_FAIL';

export const WAREHOUSE_STOCK_REORDER_REQUEST = 'WAREHOUSE_STOCK_REORDER_REQUEST';
export const WAREHOUSE_STOCK_REORDER_SUCCESS = 'WAREHOUSE_STOCK_REORDER_SUCCESS';
export const WAREHOUSE_STOCK_REORDER_FAIL = 'WAREHOUSE_STOCK_REORDER_FAIL';

export const WAREHOUSE_STOCK_ADJUST_REQUEST = 'WAREHOUSE_STOCK_ADJUST_REQUEST';
export const WAREHOUSE_STOCK_ADJUST_SUCCESS = 'WAREHOUSE_STOCK_ADJUST_SUCCESS';
export const WAREHOUSE_STOCK_ADJUST_FAIL = 'WAREHOUSE_STOCK_ADJUST_FAIL';

export const WAREHOUSE_STOCK_RESERVE_REQUEST = 'WAREHOUSE_STOCK_RESERVE_REQUEST';
export const WAREHOUSE_STOCK_RESERVE_SUCCESS = 'WAREHOUSE_STOCK_RESERVE_SUCCESS';
export const WAREHOUSE_STOCK_RESERVE_FAIL = 'WAREHOUSE_STOCK_RESERVE_FAIL';

// Stock Movement Constants
export const STOCK_MOVEMENT_LIST_REQUEST = 'STOCK_MOVEMENT_LIST_REQUEST';
export const STOCK_MOVEMENT_LIST_SUCCESS = 'STOCK_MOVEMENT_LIST_SUCCESS';
export const STOCK_MOVEMENT_LIST_FAIL = 'STOCK_MOVEMENT_LIST_FAIL';

export const STOCK_MOVEMENT_DETAILS_REQUEST = 'STOCK_MOVEMENT_DETAILS_REQUEST';
export const STOCK_MOVEMENT_DETAILS_SUCCESS = 'STOCK_MOVEMENT_DETAILS_SUCCESS';
export const STOCK_MOVEMENT_DETAILS_FAIL = 'STOCK_MOVEMENT_DETAILS_FAIL';

export const STOCK_MOVEMENT_CREATE_REQUEST = 'STOCK_MOVEMENT_CREATE_REQUEST';
export const STOCK_MOVEMENT_CREATE_SUCCESS = 'STOCK_MOVEMENT_CREATE_SUCCESS';
export const STOCK_MOVEMENT_CREATE_FAIL = 'STOCK_MOVEMENT_CREATE_FAIL';

export const STOCK_MOVEMENT_SUMMARY_REQUEST = 'STOCK_MOVEMENT_SUMMARY_REQUEST';
export const STOCK_MOVEMENT_SUMMARY_SUCCESS = 'STOCK_MOVEMENT_SUMMARY_SUCCESS';
export const STOCK_MOVEMENT_SUMMARY_FAIL = 'STOCK_MOVEMENT_SUMMARY_FAIL';

export const STOCK_MOVEMENT_EXPORT_REQUEST = 'STOCK_MOVEMENT_EXPORT_REQUEST';
export const STOCK_MOVEMENT_EXPORT_SUCCESS = 'STOCK_MOVEMENT_EXPORT_SUCCESS';
export const STOCK_MOVEMENT_EXPORT_FAIL = 'STOCK_MOVEMENT_EXPORT_FAIL';

// Inventory Transfer Constants
export const INVENTORY_TRANSFER_LIST_REQUEST = 'INVENTORY_TRANSFER_LIST_REQUEST';
export const INVENTORY_TRANSFER_LIST_SUCCESS = 'INVENTORY_TRANSFER_LIST_SUCCESS';
export const INVENTORY_TRANSFER_LIST_FAIL = 'INVENTORY_TRANSFER_LIST_FAIL';

export const INVENTORY_TRANSFER_DETAILS_REQUEST = 'INVENTORY_TRANSFER_DETAILS_REQUEST';
export const INVENTORY_TRANSFER_DETAILS_SUCCESS = 'INVENTORY_TRANSFER_DETAILS_SUCCESS';
export const INVENTORY_TRANSFER_DETAILS_FAIL = 'INVENTORY_TRANSFER_DETAILS_FAIL';

export const INVENTORY_TRANSFER_CREATE_REQUEST = 'INVENTORY_TRANSFER_CREATE_REQUEST';
export const INVENTORY_TRANSFER_CREATE_SUCCESS = 'INVENTORY_TRANSFER_CREATE_SUCCESS';
export const INVENTORY_TRANSFER_CREATE_FAIL = 'INVENTORY_TRANSFER_CREATE_FAIL';

export const INVENTORY_TRANSFER_APPROVE_REQUEST = 'INVENTORY_TRANSFER_APPROVE_REQUEST';
export const INVENTORY_TRANSFER_APPROVE_SUCCESS = 'INVENTORY_TRANSFER_APPROVE_SUCCESS';
export const INVENTORY_TRANSFER_APPROVE_FAIL = 'INVENTORY_TRANSFER_APPROVE_FAIL';

export const INVENTORY_TRANSFER_SHIP_REQUEST = 'INVENTORY_TRANSFER_SHIP_REQUEST';
export const INVENTORY_TRANSFER_SHIP_SUCCESS = 'INVENTORY_TRANSFER_SHIP_SUCCESS';
export const INVENTORY_TRANSFER_SHIP_FAIL = 'INVENTORY_TRANSFER_SHIP_FAIL';

export const INVENTORY_TRANSFER_RECEIVE_REQUEST = 'INVENTORY_TRANSFER_RECEIVE_REQUEST';
export const INVENTORY_TRANSFER_RECEIVE_SUCCESS = 'INVENTORY_TRANSFER_RECEIVE_SUCCESS';
export const INVENTORY_TRANSFER_RECEIVE_FAIL = 'INVENTORY_TRANSFER_RECEIVE_FAIL';

export const INVENTORY_TRANSFER_CANCEL_REQUEST = 'INVENTORY_TRANSFER_CANCEL_REQUEST';
export const INVENTORY_TRANSFER_CANCEL_SUCCESS = 'INVENTORY_TRANSFER_CANCEL_SUCCESS';
export const INVENTORY_TRANSFER_CANCEL_FAIL = 'INVENTORY_TRANSFER_CANCEL_FAIL';

// Stock Alert Constants
export const STOCK_ALERT_LIST_REQUEST = 'STOCK_ALERT_LIST_REQUEST';
export const STOCK_ALERT_LIST_SUCCESS = 'STOCK_ALERT_LIST_SUCCESS';
export const STOCK_ALERT_LIST_FAIL = 'STOCK_ALERT_LIST_FAIL';

export const STOCK_ALERT_DETAILS_REQUEST = 'STOCK_ALERT_DETAILS_REQUEST';
export const STOCK_ALERT_DETAILS_SUCCESS = 'STOCK_ALERT_DETAILS_SUCCESS';
export const STOCK_ALERT_DETAILS_FAIL = 'STOCK_ALERT_DETAILS_FAIL';

export const STOCK_ALERT_RESOLVE_REQUEST = 'STOCK_ALERT_RESOLVE_REQUEST';
export const STOCK_ALERT_RESOLVE_SUCCESS = 'STOCK_ALERT_RESOLVE_SUCCESS';
export const STOCK_ALERT_RESOLVE_FAIL = 'STOCK_ALERT_RESOLVE_FAIL';

export const STOCK_ALERT_UNRESOLVED_REQUEST = 'STOCK_ALERT_UNRESOLVED_REQUEST';
export const STOCK_ALERT_UNRESOLVED_SUCCESS = 'STOCK_ALERT_UNRESOLVED_SUCCESS';
export const STOCK_ALERT_UNRESOLVED_FAIL = 'STOCK_ALERT_UNRESOLVED_FAIL';

export const STOCK_ALERT_CRITICAL_REQUEST = 'STOCK_ALERT_CRITICAL_REQUEST';
export const STOCK_ALERT_CRITICAL_SUCCESS = 'STOCK_ALERT_CRITICAL_SUCCESS';
export const STOCK_ALERT_CRITICAL_FAIL = 'STOCK_ALERT_CRITICAL_FAIL';

// Stock Count Constants
export const STOCK_COUNT_LIST_REQUEST = 'STOCK_COUNT_LIST_REQUEST';
export const STOCK_COUNT_LIST_SUCCESS = 'STOCK_COUNT_LIST_SUCCESS';
export const STOCK_COUNT_LIST_FAIL = 'STOCK_COUNT_LIST_FAIL';

export const STOCK_COUNT_DETAILS_REQUEST = 'STOCK_COUNT_DETAILS_REQUEST';
export const STOCK_COUNT_DETAILS_SUCCESS = 'STOCK_COUNT_DETAILS_SUCCESS';
export const STOCK_COUNT_DETAILS_FAIL = 'STOCK_COUNT_DETAILS_FAIL';

export const STOCK_COUNT_CREATE_REQUEST = 'STOCK_COUNT_CREATE_REQUEST';
export const STOCK_COUNT_CREATE_SUCCESS = 'STOCK_COUNT_CREATE_SUCCESS';
export const STOCK_COUNT_CREATE_FAIL = 'STOCK_COUNT_CREATE_FAIL';

export const STOCK_COUNT_START_REQUEST = 'STOCK_COUNT_START_REQUEST';
export const STOCK_COUNT_START_SUCCESS = 'STOCK_COUNT_START_SUCCESS';
export const STOCK_COUNT_START_FAIL = 'STOCK_COUNT_START_FAIL';

export const STOCK_COUNT_RECORD_REQUEST = 'STOCK_COUNT_RECORD_REQUEST';
export const STOCK_COUNT_RECORD_SUCCESS = 'STOCK_COUNT_RECORD_SUCCESS';
export const STOCK_COUNT_RECORD_FAIL = 'STOCK_COUNT_RECORD_FAIL';

export const STOCK_COUNT_COMPLETE_REQUEST = 'STOCK_COUNT_COMPLETE_REQUEST';
export const STOCK_COUNT_COMPLETE_SUCCESS = 'STOCK_COUNT_COMPLETE_SUCCESS';
export const STOCK_COUNT_COMPLETE_FAIL = 'STOCK_COUNT_COMPLETE_FAIL';

// Analytics Constants
export const INVENTORY_ANALYTICS_REQUEST = 'INVENTORY_ANALYTICS_REQUEST';
export const INVENTORY_ANALYTICS_SUCCESS = 'INVENTORY_ANALYTICS_SUCCESS';
export const INVENTORY_ANALYTICS_FAIL = 'INVENTORY_ANALYTICS_FAIL';

// Bulk Operations Constants
export const BULK_INVENTORY_UPDATE_REQUEST = 'BULK_INVENTORY_UPDATE_REQUEST';
export const BULK_INVENTORY_UPDATE_SUCCESS = 'BULK_INVENTORY_UPDATE_SUCCESS';
export const BULK_INVENTORY_UPDATE_FAIL = 'BULK_INVENTORY_UPDATE_FAIL';

// Filter Constants
export const SET_INVENTORY_FILTERS = 'SET_INVENTORY_FILTERS';
export const CLEAR_INVENTORY_FILTERS = 'CLEAR_INVENTORY_FILTERS';
export const SET_INVENTORY_SORT = 'SET_INVENTORY_SORT';