// M-Pesa Configuration Constants
export const MPESA_CONFIG_LIST_REQUEST = 'MPESA_CONFIG_LIST_REQUEST';
export const MPESA_CONFIG_LIST_SUCCESS = 'MPESA_CONFIG_LIST_SUCCESS';
export const MPESA_CONFIG_LIST_FAIL = 'MPESA_CONFIG_LIST_FAIL';

export const MPESA_CONFIG_DETAILS_REQUEST = 'MPESA_CONFIG_DETAILS_REQUEST';
export const MPESA_CONFIG_DETAILS_SUCCESS = 'MPESA_CONFIG_DETAILS_SUCCESS';
export const MPESA_CONFIG_DETAILS_FAIL = 'MPESA_CONFIG_DETAILS_FAIL';

export const MPESA_CONFIG_SET_DEFAULT_REQUEST = 'MPESA_CONFIG_SET_DEFAULT_REQUEST';
export const MPESA_CONFIG_SET_DEFAULT_SUCCESS = 'MPESA_CONFIG_SET_DEFAULT_SUCCESS';
export const MPESA_CONFIG_SET_DEFAULT_FAIL = 'MPESA_CONFIG_SET_DEFAULT_FAIL';

export const MPESA_CONFIG_TEST_REQUEST = 'MPESA_CONFIG_TEST_REQUEST';
export const MPESA_CONFIG_TEST_SUCCESS = 'MPESA_CONFIG_TEST_SUCCESS';
export const MPESA_CONFIG_TEST_FAIL = 'MPESA_CONFIG_TEST_FAIL';

// M-Pesa Transaction Constants
export const MPESA_TRANSACTION_LIST_REQUEST = 'MPESA_TRANSACTION_LIST_REQUEST';
export const MPESA_TRANSACTION_LIST_SUCCESS = 'MPESA_TRANSACTION_LIST_SUCCESS';
export const MPESA_TRANSACTION_LIST_FAIL = 'MPESA_TRANSACTION_LIST_FAIL';
export const MPESA_TRANSACTION_LIST_RESET = 'MPESA_TRANSACTION_LIST_RESET';

export const MPESA_TRANSACTION_DETAILS_REQUEST = 'MPESA_TRANSACTION_DETAILS_REQUEST';
export const MPESA_TRANSACTION_DETAILS_SUCCESS = 'MPESA_TRANSACTION_DETAILS_SUCCESS';
export const MPESA_TRANSACTION_DETAILS_FAIL = 'MPESA_TRANSACTION_DETAILS_FAIL';
export const MPESA_TRANSACTION_DETAILS_RESET = 'MPESA_TRANSACTION_DETAILS_RESET';

export const MY_MPESA_TRANSACTIONS_REQUEST = 'MY_MPESA_TRANSACTIONS_REQUEST';
export const MY_MPESA_TRANSACTIONS_SUCCESS = 'MY_MPESA_TRANSACTIONS_SUCCESS';
export const MY_MPESA_TRANSACTIONS_FAIL = 'MY_MPESA_TRANSACTIONS_FAIL';

export const MPESA_TRANSACTION_RETRY_REQUEST = 'MPESA_TRANSACTION_RETRY_REQUEST';
export const MPESA_TRANSACTION_RETRY_SUCCESS = 'MPESA_TRANSACTION_RETRY_SUCCESS';
export const MPESA_TRANSACTION_RETRY_FAIL = 'MPESA_TRANSACTION_RETRY_FAIL';

export const MPESA_TRANSACTION_STATS_REQUEST = 'MPESA_TRANSACTION_STATS_REQUEST';
export const MPESA_TRANSACTION_STATS_SUCCESS = 'MPESA_TRANSACTION_STATS_SUCCESS';
export const MPESA_TRANSACTION_STATS_FAIL = 'MPESA_TRANSACTION_STATS_FAIL';

// Payment Initiation Constants
export const MPESA_PAYMENT_INITIATE_REQUEST = 'MPESA_PAYMENT_INITIATE_REQUEST';
export const MPESA_PAYMENT_INITIATE_SUCCESS = 'MPESA_PAYMENT_INITIATE_SUCCESS';
export const MPESA_PAYMENT_INITIATE_FAIL = 'MPESA_PAYMENT_INITIATE_FAIL';
export const MPESA_PAYMENT_INITIATE_RESET = 'MPESA_PAYMENT_INITIATE_RESET';

export const MPESA_PAYMENT_STATUS_REQUEST = 'MPESA_PAYMENT_STATUS_REQUEST';
export const MPESA_PAYMENT_STATUS_SUCCESS = 'MPESA_PAYMENT_STATUS_SUCCESS';
export const MPESA_PAYMENT_STATUS_FAIL = 'MPESA_PAYMENT_STATUS_FAIL';
export const MPESA_PAYMENT_STATUS_RESET = 'MPESA_PAYMENT_STATUS_RESET';

// M-Pesa Refund Constants
export const MPESA_REFUND_LIST_REQUEST = 'MPESA_REFUND_LIST_REQUEST';
export const MPESA_REFUND_LIST_SUCCESS = 'MPESA_REFUND_LIST_SUCCESS';
export const MPESA_REFUND_LIST_FAIL = 'MPESA_REFUND_LIST_FAIL';

export const MPESA_REFUND_DETAILS_REQUEST = 'MPESA_REFUND_DETAILS_REQUEST';
export const MPESA_REFUND_DETAILS_SUCCESS = 'MPESA_REFUND_DETAILS_SUCCESS';
export const MPESA_REFUND_DETAILS_FAIL = 'MPESA_REFUND_DETAILS_FAIL';

export const MPESA_REFUND_PROCESS_REQUEST = 'MPESA_REFUND_PROCESS_REQUEST';
export const MPESA_REFUND_PROCESS_SUCCESS = 'MPESA_REFUND_PROCESS_SUCCESS';
export const MPESA_REFUND_PROCESS_FAIL = 'MPESA_REFUND_PROCESS_FAIL';

// Payment Method Constants
export const MPESA_PAYMENT_METHOD_LIST_REQUEST = 'MPESA_PAYMENT_METHOD_LIST_REQUEST';
export const MPESA_PAYMENT_METHOD_LIST_SUCCESS = 'MPESA_PAYMENT_METHOD_LIST_SUCCESS';
export const MPESA_PAYMENT_METHOD_LIST_FAIL = 'MPESA_PAYMENT_METHOD_LIST_FAIL';

export const MPESA_PAYMENT_METHOD_CREATE_REQUEST = 'MPESA_PAYMENT_METHOD_CREATE_REQUEST';
export const MPESA_PAYMENT_METHOD_CREATE_SUCCESS = 'MPESA_PAYMENT_METHOD_CREATE_SUCCESS';
export const MPESA_PAYMENT_METHOD_CREATE_FAIL = 'MPESA_PAYMENT_METHOD_CREATE_FAIL';

export const MPESA_PAYMENT_METHOD_DELETE_REQUEST = 'MPESA_PAYMENT_METHOD_DELETE_REQUEST';
export const MPESA_PAYMENT_METHOD_DELETE_SUCCESS = 'MPESA_PAYMENT_METHOD_DELETE_SUCCESS';
export const MPESA_PAYMENT_METHOD_DELETE_FAIL = 'MPESA_PAYMENT_METHOD_DELETE_FAIL';

export const MPESA_PAYMENT_METHOD_SET_DEFAULT_REQUEST = 'MPESA_PAYMENT_METHOD_SET_DEFAULT_REQUEST';
export const MPESA_PAYMENT_METHOD_SET_DEFAULT_SUCCESS = 'MPESA_PAYMENT_METHOD_SET_DEFAULT_SUCCESS';
export const MPESA_PAYMENT_METHOD_SET_DEFAULT_FAIL = 'MPESA_PAYMENT_METHOD_SET_DEFAULT_FAIL';

// Filter Constants
export const SET_MPESA_FILTERS = 'SET_MPESA_FILTERS';
export const CLEAR_MPESA_FILTERS = 'CLEAR_MPESA_FILTERS';
export const SET_MPESA_SORT = 'SET_MPESA_SORT';